### ISSUE TITLE
Mekanism Smelting Factories Outputting wrong ingots

### ISSUE THREAD

**Issue by caek08** [WanionCane/UniDict#184] opened 2020-12-04 07:10 UTC
The Smelting Factories in Mekanism are not outputting the same ore type as regular furnaces.

**Comment by ElektroKill** [comment] 2020-12-04 08:20
I am unable to reproduce your issue:
![image](https://user-images.githubusercontent.com/37494960/101139455-dcb31580-3611-11eb-9ff7-fd1b259f42b7.png)
![image](https://user-images.githubusercontent.com/37494960/101139475-e50b5080-3611-11eb-9e36-0600c0565cda.png)
![image](https://user-images.githubusercontent.com/37494960/101139518-f2c0d600-3611-11eb-8945-0ec1d6acc19d.png)


Could you provide more details, such as forge version, mods, and versions of them, config details, etc?

**Comment by caek08** [comment] 2020-12-04 08:24
If you put ic2 copper ore in the smelting factory it was returning ic2 ingots when the default copper was set to thermal foundation. Same thing was happening for other ores and metals

**Comment by ElektroKill** [comment] 2020-12-04 13:36
Yes indeed, the integration does not modify the smelter recipes, it works fine for the enrichment chamber: 
![image](https://user-images.githubusercontent.com/37494960/101169974-071ac800-363e-11eb-953b-422bac8148e7.png)

I will work on a fix for this

**Comment by ElektroKill** [comment] 2020-12-04 14:26
Please wait patiently for the next release where the smelter and combiner will be supported.

**Closed as completed** 2020-12-04 14:25 UTC

**Comment by caek08** [comment] 2020-12-04 17:14
Thank you for the help!
