### ISSUE TITLE
Broken forge hammer strikes again

### ISSUE THREAD

**Issue by unikmhz** [WanionCane/UniDict#84] opened 2018-03-11 13:54 UTC
The problem originally described in #48 seems to resurface for me.
Versions:
* Oracle JDK 1.8.0.162.
* MC 1.12.2.
* Forge 2611.
* UniDict 1.12.2-2.4.

Installed mods with UniDict integrations:
* AE2.
* Forestry.
* Immersive Engineering.
* IndustrialCraft2.
* Industrial Foregoing.
* Mekanism.
* Thermal...

Forge hammer from IC2 can be used only once (when undamaged).
Engineer's hammer from IE cannot be used to craft tin plates at all (recipe still exists in JEI).

P.S.: Sorry to spam. I originally wrote this as an addendum to the original issue, not realizing it was closed.

**Comment by lukascernydis** [comment] 2018-03-13 23:17
Iron plates are affected too. Item casing seems OK.

**Comment by WanionCane** [comment] 2018-03-14 01:43
this bug with IC2 Forge Hammers is again caused by forge.
I tried with an older Forge version and it is working.

about IE's Hammer, it will be fixed on the next version =)

**Comment by dRsrb** [comment] 2018-03-16 10:37
Hi,

the problem persists since UniDict-1.12.2-2.4. It works just fine with UniDict-1.12.2-2.3.3.

This info may helps to find a solution.

Bye

**Closed as completed** 2018-03-17 17:55 UTC

**Comment by WanionCane** [comment] 2018-03-17 20:33
seems that by reverting a few changes solved this issue XD
could you guys try with the new version?

[UniDict-1.12.2-2.4c.jar](https://minecraft.curseforge.com/projects/unidict/files/2542099)

**Comment by unikmhz** [comment] 2018-03-18 13:11
Using version 2.4c:
* IE hammer doesn't work for some metal ingots to produce plates. The only recipes in JEI are for following ingots → plates:
  - Aluminum
  - Constantan
  - Electrum
  - Gold
  - Nickel
  - Silver
  - Steel
  - Uranium

  Notably tin, copper, iron, bronze, lead and possibly others are not there.
* IC2 hammer works with ingots when damaged, but only with ingots not in this list.

Example:
* IE hammer + Copper ingot = Nothing.
* IC2 hammer + Copper ingot = Copper plate.
* IE hammer + Gold ingot = Gold plate.
* IC2 hammer + Gold ingot = Nothing.
