### ISSUE TITLE
keepOneEntry blacklist does not prevent items from being hidden in JEI

### ISSUE THREAD

**Issue by wormzjl** [WanionCane/UniDict#192] opened 2021-01-31 07:40 UTC
**Describe the bug**
Set 
B:autoHideInJEI=true
B:keepOneEntry=true

Add something to S:keepOneEntryEntryBlackList

The item does not get stripped of its oredict entry, but the item is hidden in JEI

**Expected behavior**
Item in blacklist should not get hidden

UniDict-1.12.2-3.0.5

**Comment by ElektroKill** [comment] 2021-02-06 10:08
Hello, from what I understand you want the entries that are blacklisted from being removed from their respective ore dictionary to also not be hidden in JEI right?

**Comment by ElektroKill** [comment] 2021-02-06 10:47
I've added a new config option called `keepOneEntryDisableHideFromJEI`. if you set it to true the blacklisted entries will not be hidden from JEI. Can you please test it out in this build:
[UniDict-1.12.2-3.0.6.zip](https://github.com/WanionCane/UniDict/files/5936681/UniDict-1.12.2-3.0.6.zip)

**Comment by wormzjl** [comment] 2021-02-06 12:42
Seems like this config does not work for me, items in blacklist are still hidden

This is my config:
https://gist.github.com/wormzjl/87abdc661cc73120a4826d6b000f2ccc

I'm using this mod which adds a special iron ingot / nugget, which I'm trying to prevent it from being unified, you can test with it:
https://www.curseforge.com/minecraft/mc-mods/kitsus-forgecraft

**Comment by ElektroKill** [comment] 2021-02-06 14:36
The problem is the following: `keepOneEntryEntryBlackList` expects a list of OreDictionary entries consisting of `kind + resourceName` for example `ingotCopper` and not item stack names. If you need a config option that blacklists item stack names I will be happy to try to implement it :) I should probably add some more clarification to the config descriptions...

**Comment by wormzjl** [comment] 2021-02-06 14:39
Ah I see, actually this would be what I need - prevent certain items from being unified when the author did something weird.

**Comment by ElektroKill** [comment] 2021-02-06 14:46
Isn’t that covered by the `itemStacksNamesToIgnore` option?

in my original concept for the config option I meant a keepOneEntryStackBlacklist option which does unification but doesn’t apply the keep one entry on it.

**Comment by wormzjl** [comment] 2021-02-06 14:57
I did put these items inside that list, but apparently it gets hidden somehow.

**Comment by ElektroKill** [comment] 2021-02-06 15:15
Would an option to prevent JEI hiding on specific item stack names fix your problem?

**Comment by wormzjl** [comment] 2021-02-06 15:16
There is already a list, but
- Only works if keepOneEntry is false.

**Comment by ElektroKill** [comment] 2021-02-06 15:23
The current `autoHideInJEIEntryBlackList` uses OreDictionary entries just like the blacklists. This is why it doesn’t work with keepOneEntry.

**Comment by ElektroKill** [comment] 2021-02-09 13:25
Hello,

 I added a list to the config which allows removing certain items from JEI removal called `autoHideInJEIItemBlackList`.
Could you please see if the config option solves your problem using this build:
[UniDict-1.12.2-3.0.6.zip](https://github.com/WanionCane/UniDict/files/5951606/UniDict-1.12.2-3.0.6.zip)

**Comment by wormzjl** [comment] 2021-02-10 11:54
works great for me, thanks!

**Comment by ElektroKill** [comment] 2021-02-10 14:43
Good to hear that, will be part of the upcoming 3.0.6 release!

**Closed as completed by ElektroKill** 2021-02-10 14:43 UTC
Labels: bug
