### ISSUE TITLE
thermal expansion copper gear

### ISSUE THREAD

**Issue by Onigeshi** [WanionCane/UniDict#53] opened 2017-12-01 02:56 UTC
hi, i know its a minor issue, but this recipe.. http://prntscr.com/hhjecm the correct recipe should be only the one with the iron in the middle.. i've fixed pretty much everything with the gears ( like messing around changing the recipes to stone gear surrounded by ingots and stuff like that ) expect for this duplicate recipe which I can't find a way to disable it.. 

you should add an option in the config for disabling or restricting the mod from adding/changing recipes.. I mean as long as the mod unifies the materials it shouldn't modify or add recipes.. that should be the mod pack developer choice to add/modify/remove recipes.. I appreciate your work.. but lately I've encountered a lot of issues with recipes getting screwed..

also the plates from thermal/immersive after the unification, some use the hammer from immersiveengineering, some the hammer from IC2.. I've solved this by adding the hammer from immersiveengineering to ore dictionary in crafttweaker and editing the recipes.. but again now I have duplicated recipes which would be great if I can disable the recipe added by your mod and keep the one from craftteaker.. 

also maybe something can be done about this for those who don't know about or how to use craftteaker.. from what I've seen the hammer from immersive engineering is not added to Ore Dictionary i think.. I mean I can't see an oredict id.. on the IC2 description is shows ore:craftingToolForgeHammer but on the immersive one, nothing.. so I guess it could be a problem from their side probably..

**Comment by WanionCane** [comment] 2017-12-03 21:17
hello, about this, it is the intended behavior of Crafting Integration, if it sees that there is a recipe for Copper Gear, then it will recreate the recipes with the correct output.
if you disable Crafting Integration and try to create a Copper Gear with that exact shape that you show'd, then you will find that it will work, of course, it will probably not output Thermal Foundation Gear.

**Comment by Onigeshi** [comment] 2017-12-04 00:30
the recipe for thermal expansion has an iron ingot in the middle, I don't know what mods uses only one type of ingots for its gears.. buildcraft uses a lower tier gear to upgrade, forestry the same.. those are pretty much the most used mods and most of the modpacks uses as default the thermal expansion recipe which again has a iron ingot the middle.. anyway.. if thats the case then I will stop using it..

**Comment by WanionCane** [comment] 2017-12-04 00:57
well, you can remove the recipe after it get generated using MineTweaker, as far as I know now it is now possible to specify the exact recipe that you want remove using it's name.
Crafting Integration doesn't create new recipes, it will just standartize the output of the existing ones, but in order to do that, it must delete the old recipe, and "create" a new one with the right output, another advange of this is that it can get rid of all the duplicates.
so, even if you stop using it, you will endup with the same exact recipe, but probably not outputting thermal foundation copper.
there is a way to make Crafting Integration ignore a certain recipe, check "S:recipeToIgnoreList" on the config file. (using it can lead to duplicates)
but be sure to know the recipe name before UniDict tries to re-create it.

**Comment by Onigeshi** [comment] 2017-12-04 01:58
http://prntscr.com/hipt8q & http://prntscr.com/hiptgt both recipes are added by unidict, the top one is correct, the bottom one shouldn't be there.. the config is untouched expect for "S:ownerOfEveryThing" which only the order of the mods is changed and forestry and bigreactors have been added.. I tried to add the recipe to "S:recipeToIgnoreList" but failed in doing so.. nothing changed.. there are no changes made with crafttweaker expect for removing the iron gear from hammercore.. now my question is what am I doing wrong, or what should I do so the second recipe is not added?

**Comment by WanionCane** [comment] 2017-12-04 11:05
yeah, these recipes are made by UniDict, but, UniDict doesn't have any hardcoded recipes inside it.
they are created using previously existing recipes.
in order to make it ignore a certain recipe, you must disable Crafting Integration, in order to get the right name of the recipe that you want it to ignore.
also, with Crafting Integration disabled, could you try that full cooper gear shape that you showed? :)
just for curiosity.

**Comment by WanionCane** [comment] 2017-12-04 11:18
probably, the name of the recipe that you want to remove is "unidict:gearcopper_x1_shape. a aaa a "

**Comment by Onigeshi** [comment] 2017-12-04 15:36
with integration module disabled the recipes doesn't show anymore in JEI but it crafts a forestry gear.. so I guess I should remove the recipe for forestry gear, although in JEI all the forestry gears are hidden and I thought they will not be craftable..

http://prntscr.com/hiyqad , http://prntscr.com/hiyqg1 

i guess i should have done this from the begining.. sorry.. also is seems like forestry doesn't have a config setting to disable the gears like buildcraft and other mods have.. so I guess I need to remove them with crafttweaker

**Comment by WanionCane** [comment] 2017-12-04 15:57
you disabled the Integration Module or the Crafting Integration?? these two are completely different things lol
basically, disabling Integration Module disables all integrations.
so, if you really don't want this recipe, I suggest you to remove the one "created" by UnIDict.

**Comment by Onigeshi** [comment] 2017-12-04 16:28
well.. i kinda thought it wasn't the right settings but anyway it helped me find where the problem was.. I enabled it back and removed the forestry gears with crafttweaker.. so.. i guess in my stupid ways of doing things I still managed to make it work.. lul

anyway, I can't find any other setting except for that under modules.. maybe my config isn't right? https://pastebin.com/Db2iEdJW

**Comment by WanionCane** [comment] 2017-12-04 16:31
check "IntegrationModule.cfg" under "config/unidict" folder.
seems that I will have to add a way to remove recipes without needing Craftweaker for that lol.

**Comment by Onigeshi** [comment] 2017-12-04 16:41
"B:Crafting=true".. can I say that I am blind? i think not.. anyway.. I removed the forestry recipe like this.. I guess it was easier for me..

```
recipes.remove(<forestry:gear_tin>);
recipes.remove(<forestry:gear_bronze>);
recipes.remove(<forestry:gear_copper>);
```

**Comment by WanionCane** [comment] 2017-12-04 16:48
that was enough to remove that recipe? XD
anyway, I am working on the recipe removal feature on UniDict =)

**Comment by Onigeshi** [comment] 2017-12-04 16:55
yep.. that was enough.. silly me for not figuring out that from the begining.. anyway.. I don't think is really necessary as there is already something that does that but who knows.. maybe you develop that to the extent where we have the choice to not use crafttweaker for small changes.. one less mod in modpacks?

anyway, thanks and sorry if I bothered you xD

**Comment by WanionCane** [comment] 2017-12-04 17:03
I tried to remove the recipe generated by UniDict with CraftTweaker and it didn't work, I did a quick research and found that now CraftTweaker runs the scripts on PreInitialization, but UniDict fix the recipes on PostInitialization, which means, that CraftTweaker is completely unable to remove the recipes that UniDict adds, so, thanks XD, while trying to figure out the solution for your issues, I did found the solution for #44 XD
and relax, you didn't bothered me XD
so, I am closing this. =P

**Closed as completed by WanionCane** 2017-12-04 17:03 UTC
