### ISSUE TITLE
IC2 Forge Hammer broken 1.12.2

### ISSUE THREAD

**Issue by Ermen07** [WanionCane/UniDict#48] opened 2017-11-21 15:16 UTC
![screenshot_1](https://user-images.githubusercontent.com/18754622/33080023-590b1128-ced7-11e7-906a-2041da1b96f7.png)
![screenshot_2](https://user-images.githubusercontent.com/18754622/33080029-5b86bef2-ced7-11e7-8865-2f0d2069924c.png)

**Comment by WanionCane** [comment] 2017-11-22 16:52
weird, I tried here and it is working fine

**Comment by Grzeszyk** [comment] 2017-11-23 00:44
Same here - IC2 Forge hammer recipes work only with a mint hammer (no damage / 80 uses). Running MC 1.12.2, Forge 14.23.0.2546, UniDict 1.12.2-1.2 (stock config), IC2 2.8.27-ex112 and a moderate amount of other mods, notably Thermal*, Mekanism, Immersive Engineering, Forestry and CraftTweaker2 (with absolutely no scripts; a leftover of my own attempt at metals unification). More info on demand :)

EDIT: Problem exists only when hammering ingots into plates, plates -> item casings works fine.

**Comment by WanionCane** [comment] 2017-11-25 14:37
really weird, for me it is working fine.
but there is an alternative, the Engineer's Hammer (from Immersive Engineering) can also craft plates.

**Comment by Grzeszyk** [comment] 2017-11-25 19:08
It can, but not from tin. This means wasting a metric f**kton of iron ingots for 6 or so forge hammers required to make tin plates required for tin cable and such, to get a metal former up and running.
But since you can't replicate the bug, I guess we'll have to deal with it :)

**Comment by WanionCane** [comment] 2017-11-25 19:12
I released a new version, could you please, try with it when curse approve the file to see if the issue is still happening?

**Comment by Grzeszyk** [comment] 2017-11-25 19:27
Unfortunately, same thing in 1.3.
But like I said, don't worry about it too much - pretty much every mod is in some kind of alpha/beta state for 1.12 atm, so stuff is bound to break. Probably not your mod's fault anyway :)
![2017-11-25_20 24 25](https://user-images.githubusercontent.com/33915603/33233964-00172444-d21f-11e7-9ccd-7d39986d8b2e.png)

**Comment by WanionCane** [comment] 2017-11-25 19:56
could you disable crafting integration to see if this keep happening?

**Comment by Grzeszyk** [comment] 2017-11-25 20:01
Do you mean setting B:IndustrialCraft2=false in config\unidict\IntegrationModule.cfg?
If yes, then no, the recipe still doesn't work.

**Comment by WanionCane** [comment] 2017-11-25 20:09
no, I mean Crafting
B:Crafting=true

**Comment by Grzeszyk** [comment] 2017-11-25 20:15
Yes, setting B:Crafting=false fixed it.

**Comment by WanionCane** [comment] 2017-11-25 20:51
okay, so the issue is caused by Crafting Integration, thanks, now I know what to look at =)
may take awhile to fix this, due to the complexity of the Crafting Integration.

**Comment by Grzeszyk** [comment] 2017-11-25 20:57
I'm glad to be of assistance. Keep up the good work with this awesome mod :)

**Comment by WanionCane** [comment] 2017-11-27 12:26
could you try with this? UniDict-1.12.2-1.3b.jar [Curse](https://minecraft.curseforge.com/projects/unidict/files/2504037) or alternatively [GitHub](https://github.com/WanionCane/UniDict/releases/tag/UniDict-1.12.2-1.3b)

**Comment by Gamephantom** [comment] 2017-11-27 12:56
This build fixed the issue on my client :)

**Comment by Grzeszyk** [comment] 2017-11-27 13:05
For me it still doesn't work (I switched B:Crafting back to true again). :(

**Comment by WanionCane** [comment] 2017-11-27 13:07
weird... is your forge updated?

**Comment by Grzeszyk** [comment] 2017-11-27 13:21
Ahh, there you go :) I was on 14.23.0.2546; after updating to 14.23.1.2556 it finally works :D
Edit: The proof of the pudding is in the hammering ;)
![2017-11-27_14 21 41](https://user-images.githubusercontent.com/33915603/33268668-630328f4-d37e-11e7-94cd-753a18be34b2.png)

**Comment by WanionCane** [comment] 2017-11-27 13:24
yay! =D
hey @Ermen07, it has probably been fixed for you too, right?
I am closing this.

**Closed as completed by WanionCane** 2017-11-27 13:24 UTC

**Comment by unikmhz** [comment] 2018-03-11 07:18
This exact problem seems to resurface for me.
Versions:
* MC 1.12.2
* Forge 2611
* UniDict 1.12.2-2.4

Installed mods with UniDict integrations:
* AE2
* Forestry
* Immersive Engineering
* IndustrialCraft2
* Industrial Foregoing
* Mekanism
* Thermal...

Forge hammer from IC2 can be used only once (when undamaged).
Engineer's hammer from IE cannot be used to craft tin plates at all (recipe still exists in JEI).

**Comment by JLLeitschuh** [comment] 2018-03-22 14:41
Same bug in the Direwolf 20 modpack beta version 10.
